server:
  Port: :8003
  CtxDefaultTimeout: 12
  Mode: Development
  Debug: true

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: debug


auth:
  Auth0KeySetUrl: https://captainfresh.eu.auth0.com/.well-known/jwks.json

postgres:
  DSN: postgresql://doadmin:AVNS_TxN_lvCp_apDStW1_nc@db-postgresql-blr1-27078-do-user-12512855-0.b.db.ondigitalocean.com:25060/workroom-dev?sslmode=require
  MigrationPath: /resources/db/migrations/
